import { Course, CategoryInfo } from "@/types";

export const categories: CategoryInfo[] = [
  {
    id: "security",
    title: {
      ru: "Безопасность и антитеррор",
      kz: "Қауіпсіздік және антитеррор",
      en: "Security & Counter-Terrorism",
    },
    description: {
      ru: "Обнаружение угроз, досмотр, защита объектов и реагирование на ЧС",
      kz: "Қауіптерді анықтау, тексеру, объектілерді қорғау және ТЖ-ге ден қою",
      en: "Threat detection, inspection, facility protection and emergency response",
    },
    icon: "Shield",
  },
  {
    id: "profiling",
    title: {
      ru: "Профайлинг и визуальный досмотр",
      kz: "Профайлинг және визуалды тексеру",
      en: "Profiling & Visual Inspection",
    },
    description: {
      ru: "Распознавание подозрительного поведения и скрытых намерений",
      kz: "Күдікті мінез-құлық пен жасырын ниеттерді тану",
      en: "Recognizing suspicious behavior and hidden intentions",
    },
    icon: "Eye",
  },
  {
    id: "bas",
    title: {
      ru: "Беспилотные системы (БАС)",
      kz: "Ұшқышсыз жүйелер (БАС)",
      en: "Unmanned Systems (UAS)",
    },
    description: {
      ru: "Управление дронами и противодействие беспилотным угрозам",
      kz: "Дрондарды басқару және ұшқышсыз қауіптерге қарсы іс-қимыл",
      en: "Drone operation and countering unmanned threats",
    },
    icon: "Plane",
  },
  {
    id: "tactical",
    title: {
      ru: "Тактическая подготовка",
      kz: "Тактикалық дайындық",
      en: "Tactical Training",
    },
    description: {
      ru: "Тактическая медицина, экстремальное вождение, охрана ЖД",
      kz: "Тактикалық медицина, экстремалды жүргізу, ТЖ қорғау",
      en: "Tactical medicine, extreme driving, railway security",
    },
    icon: "CrosshairIcon",
  },
  {
    id: "psychology",
    title: {
      ru: "Психология и коммуникации",
      kz: "Психология және коммуникациялар",
      en: "Psychology & Communications",
    },
    description: {
      ru: "Психологическая устойчивость, кризисные коммуникации, медиа",
      kz: "Психологиялық тұрақтылық, дағдарыстық коммуникациялар, медиа",
      en: "Psychological resilience, crisis communications, media",
    },
    icon: "Brain",
  },
];

export const courses: Course[] = [
  {
    id: "1",
    slug: "security-educational-ahq",
    category: "security",
    title: {
      ru: "Безопасность АХЧ образовательных учреждений",
      kz: "Білім беру мекемелерінің АШБ қауіпсіздігі",
      en: "Security for Educational Facility Staff",
    },
    shortDescription: {
      ru: "Комплексный курс по обеспечению безопасности школ, детсадов и колледжей для административно-хозяйственного персонала",
      kz: "Мектептер, балабақшалар мен колледждердің қауіпсіздігін қамтамасыз ету бойынша кешенді курс",
      en: "Comprehensive security course for schools, kindergartens and colleges administrative staff",
    },
    duration: "3 дня (24 часа)",
    format: "Очный, интерактивный",
    price: "68 000 тенге",
    groupSize: "20–25 человек",
    certificate: true,
    program: {
      ru: [
        "Законодательные основы безопасности в образовательных учреждениях",
        "Ответственность администрации за обеспечение безопасности",
        "Запрещенные предметы и порядок действий при их обнаружении",
        "Организация пропускного режима",
        "Системы видеонаблюдения, оповещения и СКУД",
        "Понятие ВУ, СВУ и их виды, признаки закладки",
        "Алгоритм действий при ЧС, угрозе теракта",
        "Элементы тактической медицины для немедицинского персонала",
        "Основы профайлинга, разрешение конфликтных ситуаций",
        "Переговорный процесс в суицид-превенции",
      ],
      kz: [
        "Білім беру мекемелеріндегі қауіпсіздіктің заңнамалық негіздері",
        "Қауіпсіздікті қамтамасыз етуге әкімшіліктің жауапкершілігі",
        "Тыйым салынған заттар және оларды табу кезіндегі іс-қимыл тәртібі",
        "Өту режимін ұйымдастыру",
        "Бейнебақылау, хабарлау жүйелері және КЕБЖ",
        "ЖҚ, ЖСҚ ұғымы және олардың түрлері",
        "ТЖ, лаңкестік қатер кезіндегі іс-қимыл алгоритмі",
        "Медициналық емес персоналға арналған тактикалық медицина элементтері",
        "Профайлинг негіздері, жанжалды жағдайларды шешу",
        "Суицидтің алдын алудағы келіссөз процесі",
      ],
      en: [
        "Legal foundations of security in educational institutions",
        "Administration responsibility for safety",
        "Prohibited items and response procedures",
        "Access control organization",
        "CCTV, alert systems and access control",
        "Explosive devices: types and concealment signs",
        "Emergency and terror threat response algorithms",
        "Tactical medicine basics for non-medical staff",
        "Profiling basics and conflict resolution",
        "Negotiation in suicide prevention",
      ],
    },
  },
  {
    id: "2",
    slug: "counter-uas-express",
    category: "bas",
    title: {
      ru: "Противодействие БАС (экспресс-курс)",
      kz: "БАС-қа қарсы іс-қимыл (экспресс-курс)",
      en: "Counter-UAS (Express Course)",
    },
    shortDescription: {
      ru: "Экспресс-курс по методам обнаружения, идентификации и нейтрализации беспилотных угроз на стратегических объектах",
      kz: "Стратегиялық объектілерде ұшқышсыз қауіптерді анықтау, сәйкестендіру және залалсыздандыру әдістері бойынша экспресс-курс",
      en: "Express course on detection, identification and neutralization of unmanned threats at strategic facilities",
    },
    duration: "3 дня (экспресс) / 5 дней (полный)",
    format: "Теория + практика",
    certificate: true,
    program: {
      ru: [
        "Правовые основы применения мер по противодействию",
        "Методы обнаружения и идентификации БАС",
        "Технические и организационные меры защиты",
        "Алгоритм действий охраны ТЭЦ",
        "Практические занятия и сценарии",
      ],
      kz: [
        "Қарсы іс-қимыл шараларын қолданудың құқықтық негіздері",
        "БАС-ты анықтау және сәйкестендіру әдістері",
        "Қорғаудың техникалық және ұйымдастырушылық шаралары",
        "ЖЭО қорғау іс-қимыл алгоритмі",
        "Практикалық сабақтар мен сценарийлер",
      ],
      en: [
        "Legal framework for countermeasures",
        "UAS detection and identification methods",
        "Technical and organizational protection measures",
        "Power plant security response algorithm",
        "Practical exercises and scenarios",
      ],
    },
  },
  {
    id: "3",
    slug: "visual-inspection",
    category: "profiling",
    title: {
      ru: "Визуальный досмотр и оценка поведения",
      kz: "Визуалды тексеру және мінез-құлықты бағалау",
      en: "Visual Inspection & Behavior Assessment",
    },
    shortDescription: {
      ru: "Распознавание потенциальных рисков, подозрительного поведения и скрытых намерений по визуальным и невербальным сигналам",
      kz: "Визуалды және вербалды емес белгілер бойынша ықтимал тәуекелдерді, күдікті мінез-құлықты тану",
      en: "Recognizing potential risks and suspicious behavior through visual and non-verbal cues",
    },
    duration: "16–40 часов (2–5 дней)",
    format: "Очный, повышение квалификации",
    certificate: true,
    program: {
      ru: [
        "Основы визуального досмотра: принципы, правовые аспекты, этические нормы",
        "Психология поведения: эмоции, стресс, ложь, признаки тревожности",
        "Оценка поведения по методикам TSA, ICAO",
        "Профайлинг без дискриминации",
        "Практические навыки: анализ видео/фото, ролевые тренинги",
        "Алгоритм действий при выявлении признаков угрозы",
        "Взаимодействие с другими службами",
      ],
      kz: [
        "Визуалды тексеру негіздері: принциптер, құқықтық аспектілер",
        "Мінез-құлық психологиясы: эмоциялар, стресс, өтірік",
        "TSA, ICAO әдістемелері бойынша мінез-құлықты бағалау",
        "Кемсітусіз профайлинг",
        "Практикалық дағдылар: бейне/фото талдау, рөлдік тренингтер",
        "Қауіп белгілерін анықтау кезіндегі іс-қимыл алгоритмі",
        "Басқа қызметтермен өзара іс-қимыл",
      ],
      en: [
        "Visual inspection fundamentals: principles, legal aspects, ethics",
        "Behavioral psychology: emotions, stress, deception, anxiety indicators",
        "Behavior assessment using TSA, ICAO methodologies",
        "Non-discriminatory profiling",
        "Practical skills: video/photo analysis, role-playing exercises",
        "Response algorithm upon detecting threat indicators",
        "Coordination with other services",
      ],
    },
  },
  {
    id: "4",
    slug: "inspection-procedures",
    category: "security",
    title: {
      ru: "Досмотровые мероприятия и спецтехсредства",
      kz: "Тексеру іс-шаралары және арнайы техникалық құралдар",
      en: "Inspection Procedures & Technical Equipment",
    },
    shortDescription: {
      ru: "Порядок, способы и методы проведения досмотра с применением технических средств",
      kz: "Техникалық құралдарды қолдана отырып тексеру жүргізу тәртібі, тәсілдері мен әдістері",
      en: "Inspection procedures, methods and use of technical detection equipment",
    },
    duration: "3–5 дней (20–36 часов)",
    format: "Очный, 8 академических часов/день",
    certificate: true,
    program: {
      ru: [
        "Теоретическая подготовка, правовые основы",
        "Типология угроз и перечень запрещенных предметов",
        "Практическая отработка: моделирование ситуаций",
        "Работа с досмотровым оборудованием",
        "Видеоматериалы и кейсы из международной практики",
        "Основы профайлинга",
      ],
      kz: [
        "Теориялық дайындық, құқықтық негіздер",
        "Қауіп типологиясы және тыйым салынған заттар тізімі",
        "Практикалық өңдеу: жағдайларды модельдеу",
        "Тексеру жабдықтарымен жұмыс",
        "Халықаралық тәжірибеден бейне материалдар мен кейстер",
        "Профайлинг негіздері",
      ],
      en: [
        "Theoretical training, legal foundations",
        "Threat typology and prohibited items",
        "Practical exercises: situation modeling",
        "Working with inspection equipment",
        "Video materials and international case studies",
        "Profiling fundamentals",
      ],
    },
  },
  {
    id: "5",
    slug: "media-crisis-communications",
    category: "psychology",
    title: {
      ru: "Медиа и кризисные коммуникации",
      kz: "Медиа және дағдарыстық коммуникациялар",
      en: "Media & Crisis Communications",
    },
    shortDescription: {
      ru: "Формирование уверенного поведения в публичной и медийной среде, работа со СМИ в кризисных ситуациях",
      kz: "Қоғамдық және медиа ортада сенімді мінез-құлықты қалыптастыру, дағдарыс жағдайларында БАҚ-пен жұмыс",
      en: "Building confident behavior in public and media environments, working with media in crisis situations",
    },
    duration: "24–48 часов",
    format: "Лекции, семинары, ролевые тренинги",
    certificate: true,
    program: {
      ru: [
        "Публичная коммуникация и профессиональный имидж",
        "Эффективное общение с гражданами, деэскалация",
        "Взаимодействие со СМИ: подготовка к интервью",
        "Кризисные коммуникации: алгоритм действий",
        "Поведение под наблюдением: камера, публика, соцсети",
      ],
      kz: [
        "Қоғамдық коммуникация және кәсіби имидж",
        "Азаматтармен тиімді қарым-қатынас, деэскалация",
        "БАҚ-пен өзара әрекеттесу: сұхбатқа дайындық",
        "Дағдарыстық коммуникациялар: іс-қимыл алгоритмі",
        "Бақылау астындағы мінез-құлық: камера, қоғам, әлеуметтік желілер",
      ],
      en: [
        "Public communication and professional image",
        "Effective communication with citizens, de-escalation",
        "Media interaction: interview preparation",
        "Crisis communications: response algorithm",
        "Behavior under observation: camera, public, social media",
      ],
    },
  },
  {
    id: "6",
    slug: "railway-station-security",
    category: "security",
    title: {
      ru: "Безопасность на объектах ЖД (вокзалы)",
      kz: "ТЖ объектілеріндегі қауіпсіздік (вокзалдар)",
      en: "Railway Station Security & Threat Response",
    },
    shortDescription: {
      ru: "Повышение личной и объектовой безопасности, навыки раннего выявления угроз на ЖД вокзалах",
      kz: "Жеке және объектілік қауіпсіздікті арттыру, ТЖ вокзалдарында қауіптерді ерте анықтау дағдылары",
      en: "Enhancing personal and facility security, early threat detection at railway stations",
    },
    duration: "3 дня (24 ч) / 5 дней (40 ч)",
    format: "Очный, теория 30% / практика 70%",
    certificate: true,
    program: {
      ru: [
        "Тактическая медицина для работников вокзала (MARCH/ABC)",
        "Профайлинг и выявление подозрительного поведения",
        "Досмотр и визуальный контроль",
        "Обнаружение взрывных устройств и подозрительных предметов",
      ],
      kz: [
        "Вокзал қызметкерлеріне арналған тактикалық медицина (MARCH/ABC)",
        "Профайлинг және күдікті мінез-құлықты анықтау",
        "Тексеру және визуалды бақылау",
        "Жарылғыш құрылғылар мен күдікті заттарды анықтау",
      ],
      en: [
        "Tactical medicine for station staff (MARCH/ABC)",
        "Profiling and suspicious behavior detection",
        "Inspection and visual control",
        "Explosive device and suspicious item detection",
      ],
    },
  },
  {
    id: "7",
    slug: "explosive-device-detection",
    category: "security",
    title: {
      ru: "Обнаружение взрывных устройств",
      kz: "Жарылғыш құрылғыларды анықтау",
      en: "Explosive Device Detection",
    },
    shortDescription: {
      ru: "Оперативно-технический осмотр объектов, помещений и транспорта на предмет обнаружения ВУ",
      kz: "ЖҚ анықтау мақсатында объектілерді, үй-жайларды және көлікті жедел-техникалық тексеру",
      en: "Technical inspection of facilities, premises and vehicles for explosive device detection",
    },
    duration: "5 дней (40 часов)",
    format: "Лекции, практика, итоговый тест",
    certificate: true,
    program: {
      ru: [
        "Понятие ВУ и СВУ, классификация, примеры маскировки",
        "Конструктивные элементы ВУ, признаки закладки",
        "Спецтехсредства при ОТО: детекторы, зеркала, робототехника",
        "Методика проведения ОТО автотранспорта и помещений",
        "Меры безопасности, безопасные расстояния",
        "Алгоритм действий при обнаружении",
      ],
      kz: [
        "ЖҚ және ЖСҚ ұғымы, жіктелуі, бүркемелеу мысалдары",
        "ЖҚ конструктивтік элементтері, қойылу белгілері",
        "ЖТТ кезіндегі арнайы техникалық құралдар",
        "Автокөлік пен үй-жайларды ЖТТ жүргізу әдістемесі",
        "Қауіпсіздік шаралары, қауіпсіз қашықтықтар",
        "Анықтау кезіндегі іс-қимыл алгоритмі",
      ],
      en: [
        "IED concepts, classification, disguise examples",
        "Structural elements of explosive devices, concealment signs",
        "Technical equipment: detectors, mirrors, robotics",
        "Vehicle and premises inspection methodology",
        "Safety measures and safe distances",
        "Response algorithm upon detection",
      ],
    },
  },
  {
    id: "8",
    slug: "uas-operator-training",
    category: "bas",
    title: {
      ru: "Подготовка операторов БАС",
      kz: "БАС операторларын дайындау",
      en: "UAS Operator Training",
    },
    shortDescription: {
      ru: "Подготовка операторов беспилотных систем для задач охраны, наблюдения и диагностики стратегических объектов",
      kz: "Стратегиялық объектілерді қорғау, бақылау және диагностика міндеттеріне арналған БАС операторларын дайындау",
      en: "Training UAS operators for security, surveillance and diagnostics of strategic facilities",
    },
    duration: "24–40 часов",
    format: "Очный, с интенсивной практикой",
    certificate: true,
    program: {
      ru: [
        "Правовые и организационные основы применения БАС",
        "Техническое устройство и эксплуатация БАС",
        "Воздушный мониторинг и патрулирование объектов",
        "Обнаружение угроз и реагирование на нештатные ситуации",
        "Анализ и интерпретация данных воздушного наблюдения",
        "Практическая отработка и квалификационный экзамен",
      ],
      kz: [
        "БАС қолданудың құқықтық және ұйымдастырушылық негіздері",
        "БАС техникалық құрылғысы мен пайдаланылуы",
        "Объектілерді әуеден мониторинг және патрульдеу",
        "Қауіптерді анықтау және төтенше жағдайларға ден қою",
        "Әуе бақылау деректерін талдау және интерпретациялау",
        "Практикалық өңдеу және біліктілік емтиханы",
      ],
      en: [
        "Legal and organizational framework for UAS deployment",
        "UAS technical design and operation",
        "Aerial monitoring and facility patrolling",
        "Threat detection and emergency response",
        "Aerial surveillance data analysis and interpretation",
        "Practical training and qualification exam",
      ],
    },
  },
  {
    id: "9",
    slug: "railway-security",
    category: "tactical",
    title: {
      ru: "Охрана железной дороги",
      kz: "Темір жолды қорғау",
      en: "Railway Security",
    },
    shortDescription: {
      ru: "Комплексный курс для сотрудников ВЖДО по обеспечению безопасности железнодорожной инфраструктуры",
      kz: "Теміржол инфрақұрылымының қауіпсіздігін қамтамасыз ету бойынша ВЖДО қызметкерлеріне арналған кешенді курс",
      en: "Comprehensive course for railway security staff on infrastructure protection",
    },
    duration: "24–48 академических часов",
    format: "Очный, с интенсивной практикой",
    certificate: true,
    program: {
      ru: [
        "Профайлинг: выявление подозрительных пассажиров",
        "Досмотр: багаж, ручная кладь, технические средства",
        "Правовые основы: законодательство РК о транспорте и охране",
        "Тактическая медицина: первая помощь при травмах на путях",
        "Оперативно-технический осмотр на предмет ВУ",
      ],
      kz: [
        "Профайлинг: күдікті жолаушыларды анықтау",
        "Тексеру: багаж, қол жүгі, техникалық құралдар",
        "Құқықтық негіздер: ҚР көлік және қорғау заңнамасы",
        "Тактикалық медицина: жолдардағы жарақаттарда алғашқы көмек",
        "ЖҚ бойынша жедел-техникалық тексеру",
      ],
      en: [
        "Profiling: identifying suspicious passengers",
        "Inspection: luggage, carry-on, technical equipment",
        "Legal framework: Kazakhstan transport and security legislation",
        "Tactical medicine: first aid for railway injuries",
        "Technical inspection for explosive devices",
      ],
    },
  },
  {
    id: "10",
    slug: "educational-institution-security",
    category: "security",
    title: {
      ru: "Охрана образовательных учреждений (ВУЗы)",
      kz: "Білім беру мекемелерін қорғау (ЖОО)",
      en: "University & College Security",
    },
    shortDescription: {
      ru: "Комплексная безопасность высших учебных заведений: антитеррор, профайлинг, медицина, пожарная безопасность",
      kz: "Жоғары оқу орындарының кешенді қауіпсіздігі: антитеррор, профайлинг, медицина, өрт қауіпсіздігі",
      en: "Comprehensive university security: counter-terrorism, profiling, medicine, fire safety",
    },
    duration: "3–5 дней",
    format: "Очный, интерактивный",
    certificate: true,
    program: {
      ru: [
        "Визуальный досмотр и профайлинг",
        "Особенности восприятия угрозы студентами",
        "Правовые основы безопасности",
        "Антитеррор: признаки подготовки теракта, эвакуация",
        "Тактическая медицина",
        "Пожарная безопасность: задымление, эвакуация, огнетушители",
        "Выявление рисков: технические, физические, психологические",
      ],
      kz: [
        "Визуалды тексеру және профайлинг",
        "Студенттердің қауіпті қабылдау ерекшеліктері",
        "Қауіпсіздіктің құқықтық негіздері",
        "Антитеррор: лаңкестікке дайындық белгілері, эвакуация",
        "Тактикалық медицина",
        "Өрт қауіпсіздігі: түтін, эвакуация, өрт сөндіргіштер",
        "Тәуекелдерді анықтау: техникалық, физикалық, психологиялық",
      ],
      en: [
        "Visual inspection and profiling",
        "Student threat perception specifics",
        "Legal foundations of security",
        "Counter-terrorism: attack preparation signs, evacuation",
        "Tactical medicine",
        "Fire safety: smoke, evacuation, extinguishers",
        "Risk identification: technical, physical, psychological",
      ],
    },
  },
  {
    id: "11",
    slug: "profiling-train-conductors",
    category: "profiling",
    title: {
      ru: "Профайлинг для проводников поездов",
      kz: "Пойыз жүргізушілеріне арналған профайлинг",
      en: "Profiling for Train Conductors",
    },
    shortDescription: {
      ru: "Повышение безопасности пассажиров, навыки раннего распознавания опасных ситуаций для проводников",
      kz: "Жолаушылар қауіпсіздігін арттыру, жүргізушілерге арналған қауіпті жағдайларды ерте тану дағдылары",
      en: "Enhancing passenger safety and early threat recognition skills for train conductors",
    },
    duration: "2–3 дня",
    format: "Очный, интерактивный",
    certificate: true,
    program: {
      ru: [
        "Правовые основы: права и обязанности проводников",
        "Основы профайлинга: наблюдение, сигналы тревожного поведения",
        "Распознавание людей с психологическими отклонениями",
        "Работа с пассажирами в состоянии опьянения",
        "Конфликтные ситуации с дебоширами",
        "Антитеррористическая безопасность",
        "Пожарная безопасность в поезде",
        "Тактическая медицина: первая помощь",
      ],
      kz: [
        "Құқықтық негіздер: жүргізушілердің құқықтары мен міндеттері",
        "Профайлинг негіздері: бақылау, дабыл мінез-құлық сигналдары",
        "Психологиялық ауытқулары бар адамдарды тану",
        "Мас күйдегі жолаушылармен жұмыс",
        "Бұзақылармен жанжалды жағдайлар",
        "Антитеррористік қауіпсіздік",
        "Пойыздағы өрт қауіпсіздігі",
        "Тактикалық медицина: алғашқы көмек",
      ],
      en: [
        "Legal framework: conductor rights and responsibilities",
        "Profiling basics: observation, alarming behavior signals",
        "Recognizing individuals with psychological disorders",
        "Working with intoxicated passengers",
        "Conflict situations with disruptive passengers",
        "Counter-terrorism security",
        "Fire safety on trains",
        "Tactical medicine: first aid",
      ],
    },
  },
  {
    id: "12",
    slug: "profiling-interactive",
    category: "profiling",
    title: {
      ru: "Профайлинг — интерактивный тренинг",
      kz: "Профайлинг — интерактивті тренинг",
      en: "Profiling — Interactive Training",
    },
    shortDescription: {
      ru: "Интерактивный тренинг с тестами: базовые эмоции, язык тела, признаки лжи, наблюдение",
      kz: "Тесттері бар интерактивті тренинг: базалық эмоциялар, дене тілі, өтірік белгілері",
      en: "Interactive training with tests: basic emotions, body language, deception indicators",
    },
    duration: "1–2 дня",
    format: "Интерактивный тренинг",
    certificate: true,
    program: {
      ru: [
        "Базовые эмоции по лицу: радость, злость, страх, грусть, отвращение, удивление, презрение",
        "Жесты и язык тела",
        "Речь и признаки лжи",
        "Система сигналов: мимика + жесты + речь",
        "Игры и тесты: угадывание эмоций, ложь или правда, психологический портрет",
      ],
      kz: [
        "Бет бойынша базалық эмоциялар: қуаныш, ашу, қорқыныш, қайғы",
        "Ишараттар мен дене тілі",
        "Сөйлеу және өтірік белгілері",
        "Сигнал жүйесі: мимика + ишараттар + сөйлеу",
        "Ойындар мен тесттер: эмоцияларды болжау, өтірік не шындық",
      ],
      en: [
        "Facial basic emotions: joy, anger, fear, sadness, disgust, surprise, contempt",
        "Gestures and body language",
        "Speech and deception indicators",
        "Signal system: facial expressions + gestures + speech",
        "Games and tests: emotion guessing, truth or lie, psychological portrait",
      ],
    },
  },
  {
    id: "13",
    slug: "psychological-resilience-mvd",
    category: "psychology",
    title: {
      ru: "Психологическая устойчивость сотрудников МВД",
      kz: "ІІМ қызметкерлерінің психологиялық тұрақтылығы",
      en: "Psychological Resilience for Police Officers",
    },
    shortDescription: {
      ru: "Формирование психологической устойчивости для эффективной службы в условиях стрессовой нагрузки",
      kz: "Стресстік жүктеме жағдайында тиімді қызмет үшін психологиялық тұрақтылықты қалыптастыру",
      en: "Building psychological resilience for effective service under stress",
    },
    duration: "3–5 дней",
    format: "Лекции, тренинги, ролевые игры",
    certificate: true,
    program: {
      ru: [
        "Введение в основы психологической устойчивости",
        "Эмоциональный интеллект и управление состояниями",
        "Профилактика выгорания и восстановление ресурса",
        "Стресс и конфликт: стратегии поведения",
        "Командная устойчивость и личное развитие",
      ],
      kz: [
        "Психологиялық тұрақтылық негіздеріне кіріспе",
        "Эмоционалдық интеллект және жағдайларды басқару",
        "Күйіп кетудің алдын алу және ресурсты қалпына келтіру",
        "Стресс және жанжал: мінез-құлық стратегиялары",
        "Командалық тұрақтылық және жеке даму",
      ],
      en: [
        "Introduction to psychological resilience",
        "Emotional intelligence and state management",
        "Burnout prevention and resource recovery",
        "Stress and conflict: behavioral strategies",
        "Team resilience and personal development",
      ],
    },
  },
  {
    id: "14",
    slug: "psychological-safety-crisis",
    category: "psychology",
    title: {
      ru: "Психологическая безопасность в кризисных ситуациях",
      kz: "Дағдарыс жағдайларындағы психологиялық қауіпсіздік",
      en: "Psychological Safety in Crisis Situations",
    },
    shortDescription: {
      ru: "Обеспечение психологической безопасности в коллективе, действия в условиях стресса и кризиса",
      kz: "Ұжымдағы психологиялық қауіпсіздікті қамтамасыз ету, стресс және дағдарыс жағдайларындағы іс-қимыл",
      en: "Maintaining psychological safety in teams, behavior under stress and crisis",
    },
    duration: "2–3 дня",
    format: "Лекции + практические задания",
    certificate: true,
    program: {
      ru: [
        "Понятие психологической безопасности",
        "Психология кризиса: виды, когнитивные и эмоциональные реакции",
        "Эффективное поведение в кризисной ситуации",
        "Методы саморегуляции и стабилизации",
        "Коммуникация в условиях кризиса",
        "Посткризисное восстановление",
      ],
      kz: [
        "Психологиялық қауіпсіздік ұғымы",
        "Дағдарыс психологиясы: түрлері, когнитивті және эмоционалдық реакциялар",
        "Дағдарыстық жағдайдағы тиімді мінез-құлық",
        "Өзін-өзі реттеу және тұрақтандыру әдістері",
        "Дағдарыс жағдайындағы коммуникация",
        "Дағдарыстан кейінгі қалпына келу",
      ],
      en: [
        "Concept of psychological safety",
        "Crisis psychology: types, cognitive and emotional reactions",
        "Effective behavior in crisis situations",
        "Self-regulation and stabilization methods",
        "Communication in crisis conditions",
        "Post-crisis recovery",
      ],
    },
  },
  {
    id: "15",
    slug: "tactical-medicine",
    category: "tactical",
    title: {
      ru: "Тактическая медицина",
      kz: "Тактикалық медицина",
      en: "Tactical Medicine",
    },
    shortDescription: {
      ru: "Практические навыки оказания первой медицинской помощи в тактических условиях по стандартам TCCC и TECC",
      kz: "TCCC және TECC стандарттары бойынша тактикалық жағдайларда алғашқы медициналық көмек көрсетудің практикалық дағдылары",
      en: "Practical first aid skills in tactical conditions following TCCC and TECC standards",
    },
    duration: "24–48 часов",
    format: "Очный, интенсивная практика",
    certificate: true,
    program: {
      ru: [
        "Принципы тактической медицины в зоне активного риска",
        "Оценка обстановки, сортировка пострадавших (Triage)",
        "Контроль критических кровотечений: турникеты, гемостатики",
        "Проходимость дыхательных путей",
        "Наложение жгутов, повязок, работа с пневмотораксом",
        "Эвакуация пострадавших (CASEVAC, MEDEVAC)",
        "Психологическая устойчивость и принятие решений под стрессом",
        "Командное взаимодействие при оказании помощи",
      ],
      kz: [
        "Белсенді тәуекел аймағындағы тактикалық медицина принциптері",
        "Жағдайды бағалау, зардап шеккендерді сұрыптау (Triage)",
        "Сыни қан кетуді бақылау: турникеттер, гемостатиктер",
        "Тыныс алу жолдарының өткізгіштігі",
        "Жгуттар, таңғыштар салу, пневмоторакспен жұмыс",
        "Зардап шеккендерді эвакуациялау (CASEVAC, MEDEVAC)",
        "Стресс жағдайында психологиялық тұрақтылық пен шешім қабылдау",
        "Көмек көрсету кезінде командалық өзара іс-қимыл",
      ],
      en: [
        "Tactical medicine principles in active risk zones",
        "Situation assessment, casualty triage",
        "Critical bleeding control: tourniquets, hemostatics",
        "Airway management",
        "Tourniquet and bandage application, pneumothorax management",
        "Casualty evacuation (CASEVAC, MEDEVAC)",
        "Psychological resilience and decision-making under stress",
        "Team coordination during care provision",
      ],
    },
  },
  {
    id: "16",
    slug: "extreme-driving",
    category: "tactical",
    title: {
      ru: "Экстремальное вождение",
      kz: "Экстремалды жүргізу",
      en: "Extreme Driving",
    },
    shortDescription: {
      ru: "Профессиональная подготовка водителей к управлению автомобилем в экстремальных условиях",
      kz: "Жүргізушілерді экстремалды жағдайларда автомобильді басқаруға кәсіби дайындау",
      en: "Professional driver training for vehicle control in extreme conditions",
    },
    duration: "24–40 часов (3–5 дней)",
    format: "Теория → симулятор → практика",
    certificate: true,
    program: {
      ru: [
        "Теория: динамика автомобиля, сцепление, безопасное маневрирование",
        "Симуляторы: гололед, дождь, аквапланирование, экстренное торможение",
        "Предотвращение и вывод из заноса",
        "Экстренное торможение и объезд препятствий",
        "Маневрирование в ограниченном пространстве",
        "Развороты на 180° и 360°",
        "Действия при угрозе столкновения или нападения",
        "Оборонительное и защитное вождение",
      ],
      kz: [
        "Теория: автомобиль динамикасы, ілінісу, қауіпсіз маневрлеу",
        "Симуляторлар: мұзданған жол, жаңбыр, аквапланирование",
        "Сырғанаудан алдын алу және шығару",
        "Шұғыл тежеу және кедергілерден жалтару",
        "Шектеулі кеңістікте маневрлеу",
        "180° және 360° бұрылыстар",
        "Соқтығысу немесе шабуыл қаупі кезіндегі әрекеттер",
        "Қорғаныс жүргізу",
      ],
      en: [
        "Theory: vehicle dynamics, traction, safe maneuvering",
        "Simulators: ice, rain, aquaplaning, emergency braking",
        "Skid prevention and recovery",
        "Emergency braking and obstacle avoidance",
        "Maneuvering in confined spaces",
        "180° and 360° turns",
        "Actions during collision or attack threat",
        "Defensive and protective driving",
      ],
    },
  },
  {
    id: "17",
    slug: "counter-uas-full",
    category: "bas",
    title: {
      ru: "Противодействие БАС (полный курс)",
      kz: "БАС-қа қарсы іс-қимыл (толық курс)",
      en: "Counter-UAS (Full Course)",
    },
    shortDescription: {
      ru: "Комплексный курс: подготовка операторов БАС + методы противодействия беспилотным угрозам",
      kz: "Кешенді курс: БАС операторларын дайындау + ұшқышсыз қауіптерге қарсы іс-қимыл әдістері",
      en: "Comprehensive course: UAS operator training + counter-unmanned threat methods",
    },
    duration: "5–7 дней (40+ часов)",
    format: "Очный, теория + полигон",
    certificate: true,
    program: {
      ru: [
        "Операторы БАС: основы пилотирования, нормативная база",
        "Планирование полетов и техобслуживание",
        "Противодействие БАС: анализ угроз",
        "Техсредства обнаружения",
        "Методы противодействия: РЭБ, перехват, БАС-перехватчики",
        "Организация охраны ТЭЦ от беспилотных угроз",
        "Учебные сценарии: разведка, охрана, нейтрализация",
        "Летные тренировки на полигоне",
      ],
      kz: [
        "БАС операторлары: пилоттау негіздері, нормативтік база",
        "Ұшуларды жоспарлау және техникалық қызмет көрсету",
        "БАС-қа қарсы іс-қимыл: қауіптерді талдау",
        "Анықтаудың техникалық құралдары",
        "Қарсы іс-қимыл әдістері: РЭК, ұстап алу",
        "ЖЭО-ны ұшқышсыз қауіптерден қорғауды ұйымдастыру",
        "Оқу сценарийлері: барлау, қорғау, залалсыздандыру",
        "Полигондағы ұшу жаттығулары",
      ],
      en: [
        "UAS operators: piloting fundamentals, regulatory framework",
        "Flight planning and maintenance",
        "Counter-UAS: threat analysis",
        "Detection equipment",
        "Countermeasures: EW, interception, interceptor UAS",
        "Power plant protection from unmanned threats",
        "Training scenarios: reconnaissance, security, neutralization",
        "Flight training at the range",
      ],
    },
  },
];
